### ISSUE TITLE
What about the documentation about TestAdaper?

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/bot-docs#1156]
I see now the `TestAdapter` and the `TestFlow`.

I think it is important to write a guidelines about writing tests with these tools.

I can't write the documentation myself because I have a full stack of other things to write about, and I'm not working on Microsoft ;-)

Also, my English is not the best.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1718fa-0745-3fee-6ef5-18e36b61fabf
* Version Independent ID: fd9ef97f-4540-e624-d459-c076e94a50ad
* Content: [Create a bot with the Bot Framework SDK for .NET - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/dotnet/bot-builder-dotnet-sdk-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-sdk-quickstart.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
We intend to update the Debugging section, including additional topics, such as this one. However, our schedule is not firm yet.

**Comment by Kaiqb** [comment]
In terms of testing bots, this is the [article ](https://docs.microsoft.com/en-us/azure/bot-service/unit-test-bots?view=azure-bot-service-4.0&tabs=csharp) we just published.

**Comment by baruchiro** [comment]
Wonderful!
Nowadays, writing unit tests is part of writing the code itself, and it must come along with the documentation of the code.

I still do not see documentation for the `TestAtapter` with the `TestFlow`. Is this will be in another article for integration tests?
