### ISSUE TITLE
steps cannot be followed in this tutorial 

### ISSUE THREAD

**Issue by vivekjainAco** [MicrosoftDocs/bot-docs#422]
hi, 
I tried to follow the steps through the CLI which are mentioned in : https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/14.nlp-with-dispatch.

I cannot proceed becase of this error: 

Der Befehl "az" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

which is coming when I run the command to connect LUIS:

msbot clone services --name "&lt;NAME&gt;" --luisAuthoringKey "&lt;YOUR AUTHORING KEY&gt;" --folder "DeploymentScripts/MsbotClone" --location "westus".

when i run this, i get a list of services to be created, when I say yes, its gives the error and say like this:

NOTE: You did not complete clone process.
To delete the group and resources run:
az group delete -g Azurenlpbot --no-wait

so I am not sure what is this az which is not available.

Please help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Integrate multiple LUIS and QnA services with the Dispatch tool - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by ivorb** [comment]
az is a command line tool for azure, which I'm sure is in the script you're trying to run. Have you ensured you have up to date CLI BotBuilder tools, as the earlier section of that linked README talks about? And have you put your specific name and authoring key, and ensured that you're in the right local directory?

**Comment by ivorb** [comment]
possibly related? There seem to be a few issues with msbot/az clone

https://github.com/Microsoft/botbuilder-tools/issues/596

**Comment by vivekjainAco** [comment]
I tried to follow the steps exactly they are mentioned in the documentation. have the latest CLI tools. 
Okay, then Shall I wait until the documentation is corrected or the MSbot tool to follow this tutorial?

**Comment by CathyQian** [comment]
I'm working on it now and will get back to you soon.

**Comment by ShawnXiao105** [comment]
I still cannot pass `msbot clone service` even if I set appId and appSecret. And I found another bug that if the appSecret contains two sequences `|` like `||`. The program just misses the part after the `||`.  Thanks
