### ISSUE TITLE
Bullet needed for SetAccessors

### ISSUE THREAD

**Issue by arafattehsin** [MicrosoftDocs/bot-docs#609]
In 'How the state property accessor methods work' section, another bullet is required for set accessors. 

I am also not able to edit this particular file in GitHub because of 404 error. Kindly have a look. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1795c22-9e0f-8a69-a517-ffbe38a2cd30
* Version Independent ID: 9d2c1569-6d6f-97fa-881d-b4a0f61623a2
* Content: [Managing State - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-state?view=azure-bot-service-4.0#how-the-state-property-accessor-methods-work)
* Content Source: [articles/v4sdk/bot-builder-concept-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-state.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by arafattehsin** [comment]
Closing it as I have found it fixed in live-sync branch.

**Comment by martinlarosa** [comment]
This is still broken.
If the property is in the cache, return it. Otherwise, get it from the state management object. (If it is not yet in state, use the factory method provided in the accessors get call.) -The accessor's set method:
